### ISSUE TITLE
Top rage-x search filters do not appear to affect the file list below.

### ISSUE THREAD

**Issue by Michael82548** [Rob--W/crxviewer#107]
I am using the latest version directly from source (603e4fc)

If this is intended, then there should be a separate filter below next to the file list below.
![image](https://user-images.githubusercontent.com/53535277/131204173-aa3180b1-3ade-4e50-b559-2565ab58fab9.png)

**Comment by Rob--W** [comment]
I don't understand the reported issue. What are you trying to show in your image (including the the black circles in your image)? Could you describe the steps that you have followed, the actual result and the expected result? Please be sufficiently detailed so I can try to reproduce your issue.
