### ISSUE TITLE
Modern JS/ES6+ syntax beautified incorrectly

### ISSUE THREAD

**Issue by mattbroussard** [Rob--W/crxviewer#110]
For example, [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) is treated as a ternary operator and becomes confusing to read. The original code:
![image](https://user-images.githubusercontent.com/3347176/140022248-a43bdf01-5de5-4c9c-82e3-9cf085f839c4.png)
becomes this:
![image](https://user-images.githubusercontent.com/3347176/140022221-0bb69ef9-629d-4707-9b8c-109b27f5e663.png)

This could probably be solved just by updating [`js-beautify`](https://www.npmjs.com/package/js-beautify) to the latest version (currently seem to be using a 3-year-old version).

**Comment by Rob--W** [comment]
Fixed in 1.6.12.
