### ISSUE TITLE
Not working for addons.thunderbird.net

### ISSUE THREAD

**Issue by PhoenixIV** [Rob--W/crxviewer#111]
May you add support for Thunderbird xpi files?
Page: https://addons.thunderbird.net/

**Comment by Rob--W** [comment]
I have added support for viewing the source code of Thunderbird extensions in 1.6.12.

**Comment by PhoenixIV** [comment]
Thanks!

Something I do not know about, but if no major rebuild is required you might also want to put this in the Thunderbird addon repository. Personally I am okay with switching to Firefox for inspection.

**Comment by Rob--W** [comment]
I suggest to use the Firefox version.
