### ISSUE TITLE
Beautify Source Code When Zipped

### ISSUE THREAD

**Issue by INDA010010** [Rob--W/crxviewer#112]
Hi,
I've been using CRXViewer for a little while.
I really like that the source code is beautified when you open a file using the extension, I just wish it would do the same when downloading the source code as a ZIP file.

Do anyone know if this is even possible?

**Comment by Rob--W** [comment]
The viewer only offers the ability to download the whole zip, or the (original) file. There is no option to download a beautified version. If you'd like, you could copy the file content to https://beautifier.io/ and then save the result.
