### ISSUE TITLE
Web version not working for viewing JS/CSS files

### ISSUE THREAD

**Issue by LunarTwilight** [Rob--W/crxviewer#113]
When I try to view JS/CSS via the online version, it doesn't work and these errors are in my console
> Uncaught DOMException: Failed to construct 'Worker': Script at 'chrome-extension://cafckninonjkogajnihihlnnimmkndgf/js/worker-beautify.js' cannot be accessed from origin 'https://robwu.nl'.
    at https://robwu.nl/crxviewer/lib/beautify/beautify.js:21:18
    at https://robwu.nl/crxviewer/lib/beautify/beautify.js:115:3

> crxviewer.js:494 Uncaught TypeError: Cannot read properties of undefined (reading 'getType')
    at callback (crxviewer.js:494:26)
    at crxviewer.js:260:13
    at zip.js:577:7
    at EfficientTextWriter.getData (efficienttextwriter.js:29:5)
    at getWriterData (zip.js:576:13)
    at onflush (zip.js:311:4)
    at Worker.onmessage (zip.js:346:7)

**Comment by Rob--W** [comment]
Fixed in the latest version at https://robwu.nl/crxviewer/
