### ISSUE TITLE
Support for Microsoft Edge Chromium Addons

### ISSUE THREAD

**Issue by 2Seven72** [Rob--W/crxviewer#114]
Hi,
Could you please add support for Microsoft Edge Addons in the next revision of Extension Source Viewer?

Greetings and Thanks ;)

**Comment by yfdyh000** [comment]
dupe of #43

**Comment by 2Seven72** [comment]
Very nice, Thank You

**Comment by 2Seven72** [comment]
Very nice, thank you ;)

**Comment by 2Seven72** [comment]
> dupe of #43

Very nice, thank you ;)

**Comment by Rob--W** [comment]
This has been implemented (#43), I'll publish a new version shortly.

**Comment by 2Seven72** [comment]
Thank You so much ;)

**Comment by Rob--W** [comment]
I have submitted version 1.6.12 to Firefox's add-on gallery, the Chrome Web Store and Opera's addon gallery. That version includes support for viewing Edge extensions.
