### ISSUE TITLE
[Bug] Stopped working on Firefox Add-ons

### ISSUE THREAD

**Issue by emvaized** [Rob--W/crxviewer#115]
Extension stopped working on https://addons.mozilla.org/

When clicking on "View source", it gives this error:
`Failed to load https://addons.mozilla.org/firefox/downloads/latest/noscript/platform:3/noscript.xpi. Server responded with 504 GATEWAY_TIMEOUT`

CRX Viewer: 1.6.11
Platform: Firefox 98.0.1

**Comment by Shadow-of-Colossus** [comment]
I get the same thing... in clean profiles on v87 v97 and the newest v98. The strange thing is I have it installed on Edge and I can view the source code or download as a zip file from the Mozilla Addon site.

**Comment by Rob--W** [comment]
Version 1.6.12 has been published, with a fix for this bug.
