### ISSUE TITLE
Download as zip = "download failed"

### ISSUE THREAD

**Issue by led9** [Rob--W/crxviewer#123]
In Firefox Nightly 64bit, Windows 10,  your extension,
page https://addons.mozilla.org/ru/firefox/addon/crxviewer/
click on "crx" in address bar, click on button "Download as zip" - it asks where to save the file, BUT NOT save. 
In firefox's downloads for this wrote = "download failed"
if you select "copy download link" on failed download, this link copy:
blob:moz-extension://611ee09c-2119-463c-bd79-0e69c30e5f99/5e417805-c7be-4a50-8d2d-29404371f00f

if click on "crx" in address bar, click on button "View source" = page with source appears, click on "Download" on it = it asks where to save the file, AND save file successfully! 

Please fix "Download as zip"!

**Comment by led9** [comment]
Disabled all other extensions except for your extension = the error repeats.
firefox download restrictions disabled

Successful download via "View source" = page with source appears, click on "Download"
link is
blob:moz-extension://611ee09c-2119-463c-bd79-0e69c30e5f99/a2303fac-afb8-45e4-af33-bec3f7506ddc
As you can see, another link, maybe the link( from "Download as zip") is wrong, that's why it doesn't work

**Comment by Rob--W** [comment]
This was fixed in version 1.6.12, by c417659e90a510dfb007e8161bf6a36aaf44c809.
