### ISSUE TITLE
Add a toggle to un-minify/de-obfuscate code 

### ISSUE THREAD

**Issue by leodoi3** [Rob--W/crxviewer#127]
Sometimes I get  source code that is minified which makes it hard to read. Could you add a toggle that unminifies the code?

**Comment by gwarser** [comment]
![image](https://user-images.githubusercontent.com/886325/203709995-7fd5d32b-0a1a-49ed-85e6-793bf121d447.png)

**Comment by Rob--W** [comment]
It already exists :)

**Comment by leodoi3** [comment]
That is not the same. For example the variables are not using coherent names.

**Comment by Rob--W** [comment]
When code is obfuscated or minified, variable names are lost. There is no general way to get the desired information back.
