### ISSUE TITLE
Stopped working on Chrome recently

### ISSUE THREAD

**Issue by lethefrost** [Rob--W/crxviewer#131]
Just suddenly notice that the button remains grayed out and unclickable on Chrome extension store pages (and everywhere else). The last time I used it was a week ago, and it was still working then.

**Comment by Rob--W** [comment]
I have uploaded version 1.7.0 to the Chrome Web Store, which fixes two issues that could potentially be causing this issue:

- The Chrome Web Store has a new URL (#134)
- Chrome has had some bugs that results in the inability to register the correct click handler. I made some fixes in version 1.7.0. for that.

Once version 1.7.0 has been approved by the CWS, please give it a try and let me know if you're still having the issue.
