### ISSUE TITLE
doesn't activate when on extension

### ISSUE THREAD

**Issue by jots** [Rob--W/crxviewer#136]
using chrome, it doesn't light up when on an extension page.
I think the problem is that `cws_download_pattern`  is no longer matching because they don't have the full url in the page anymore.

**Comment by Rob--W** [comment]
Duplicate of #134.

I have already committed a patch that fixes this, but I haven't published an update yet.

**Comment by jots** [comment]
Thanks.  I downloaded the latest from github and am running it as an unpacked extension and it's still not working.  perhaps I'm doing something wrong.

**Comment by Rob--W** [comment]
Can you share the steps so I can try to reproduce your problem?
