### ISSUE TITLE
Do not show up on Chrome 50

### ISSUE THREAD

**Issue by oldergod** [Rob--W/crxviewer#22]
The icon do not show up anymore in the adress bar inside the Chrome Web Store.

**Comment by Rob--W** [comment]
The icon does show up and works here. Did you maybe hide the icon or put the icon in the hamburger menu?

**Comment by oldergod** [comment]
Sorry, you are right. I was used to get it in the adress bar and did not think it would move to the toolbar and further.

Thank you.

**Comment by Rob--W** [comment]
No problem. If you want it back, you can move it out again.

**Comment by oldergod** [comment]
Yes indeed, but no more pageAction right? Is it a API change or did you modify the app?

**Comment by Rob--W** [comment]
It is caused by a change in Chrome: https://crbug.com/403823

Hopefully the UX will improve for pageActions, because the current situation is not nice: https://crbug.com/597657

**Comment by Hrxn** [comment]
Just installed the extension and noticed this as well. At least the issue search seems to work.

And thank you for the links in the comment above, really insightful. I thought something was broken, but apparently they changed it _intentionally_ ...

**Comment by Rob--W** [comment]
My extension also adds a context menu entry to webstore pages (and extension links), so you can also use the context menu to view an extension's source code. This is what I have been using since the button moved into the menu.

If you don't see a context menu item, visit the extension's settings page (because the context menu is optional).

**Comment by Hrxn** [comment]
Well, it is working. Just always the (grayed out) icon next to the address bar, on every non Web store/extension page. 

By the way, is there some way to change (or hide completely) the icon from inside the wrench/3-dot menu, i.e. after it already has been "hidden"?

**Comment by Rob--W** [comment]
> Well, it is working. Just always the (grayed out) icon next to the address bar, on every non Web store/extension page. 

The icon can be hidden (moved into the wrench/3-dot) ny right-clicking on the icon. You already know that, since you're asking the next question.

> By the way, is there some way to change (or hide completely) the icon from inside the wrench/3-dot menu, i.e. after it already has been "hidden"?

No, that is not possible. This is an intentional design choice of Chrome, to make users aware of which extensions they have installed.
