### ISSUE TITLE
Can't view source of ChromeOS-only extensions

### ISSUE THREAD

**Issue by mdamien** [Rob--W/crxviewer#23]
Like this one for example: https://chrome.google.com/webstore/detail/speedy-cars-memory-game/macblkncmhkhcfpjnjdidjockdbagbgk

EDIT: To be clear, I know why it's not working (the url we all use to download the crx), just want to report it

**Comment by Rob--W** [comment]
The downloads are currently optimized for your own OS.

As a work-around, edit the URL and set the `os` parameter to `cros`, e.g.

<code>chrome-extension://jifpbeccnghkjeaalbbjmodiffmgedin/crxviewer.html?crx=https%3A%2F%2Fclients2.google.com%2Fservice%2Fupdate2%2Fcrx%3Fresponse%3Dredirect%26<strong>os%3Dcros</strong>%26arch%3Dx86-64%26nacl_arch%3Dx86-64%26prod%3Dchromiumcrx%26prodchannel%3Dunknown%26prodversion%3D50.0.2661.94%26x%3Did%253Dmacblkncmhkhcfpjnjdidjockdbagbgk%2526uc</code>

This particular extension just contains an APK file + some metadata.

**Comment by mdamien** [comment]
ok, so, another way to fix that would be to let the user change the OS via a dropdown or to check automatically the download response (empty response here) and check for other OS.

But thanks, let's close it then, that's another bug/feature maybe.

**Comment by Rob--W** [comment]
There are more parameters that can be varied (e.g. when an extension contains NaCl modules). Showing a UI (dropdown) to change the parameters when the CRX cannot be downloaded sounds like a good idea.

Running APKs on Chrome OS is called ARC, see https://developer.chrome.com/apps/getstarted_arc

**Comment by Rob--W** [comment]
:smile:
