### ISSUE TITLE
Enabling "Allow access to all URLs" option breaks extension downloading

### ISSUE THREAD

**Issue by ngyikp** [Rob--W/crxviewer#26]
User-agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.80 Safari/537.36

If you enable "Allow access to all URLs", then it can't download any extensions anymore because it's missing an `Origin` header when you try to proxy through `cors-everywhere.heroku.com`

Compare:
![parallels picture 8](https://cloud.githubusercontent.com/assets/6135313/18115840/512801d6-6f75-11e6-89bd-b45c907e6cac.png)
and
![parallels picture 5](https://cloud.githubusercontent.com/assets/6135313/18115841/562b5642-6f75-11e6-80c5-d1f779c214c1.png)

Problem is [the preprocessor does not look inside subfolders](https://github.com/Rob--W/crxviewer/blob/7439cc2149b887c44b0613a48b19d0d4db0eb44e/make.js#L35) and [the code that handles the downloading](https://github.com/Rob--W/crxviewer/blob/bf881fd60490e00d86933fdf0281f6be3c60f60a/src/lib/crx-to-zip.js#L99) is located on `src/lib/`

Simple fix would be just include the file in the preprocess config:
```js
            [SRC_DIR + 'lib/crx-to-zip.js', dest_dir + 'lib/crx-to-zip.js'],
```

**Comment by Rob--W** [comment]
Oops.. Can't believe that I missed this during testing. Do you want to send a PR?

**Comment by Rob--W** [comment]
Published, thanks again for bringing this to my attention.
