### ISSUE TITLE
Support view source of Microsoft Edge extensions

### ISSUE THREAD

**Issue by Rob--W** [Rob--W/crxviewer#43]
Apparently it is possible to submit Edge extensions: https://stackoverflow.com/questions/38803483/how-to-publish-edge-extensions-on-the-windows-store

For example, https://www.microsoft.com/en-us/store/p/lastpass-free-password-manager/9nblggh4v7x0

The "Get the app" button is only clickable when the user agent is Microsoft Edge, and the link points to `ms-windows-store://pdp/?productid=9NBLGGH4V7X0&referrer=unistoreweb&scenario=click&webig=b8ef09a9-c3a5-465e-8feb-05e26c67b366&websession=4a81cfb5acb24036986abea0705a45b4`

Now, if there was a way to convert the store's URL to a URL from where the extension package can be downloaded as a zip-like file, then it could be displayed in the extension source viewer.

**Comment by Noitidart** [comment]
Super much love! :D

**Comment by KrasnayaPloshchad** [comment]
MS Edge extensions now available at https://microsoftedge.microsoft.com/addons/category/Edge-Extensions

**Comment by utkarshspat** [comment]
@Rob--W I just created a pull request to add support for the Microsoft Edge extensions. Please review it: https://github.com/Rob--W/crxviewer/pull/101.

**Comment by minig0d** [comment]
> Now, if there was a way to convert the store's URL to a URL from where the extension package can be downloaded as a zip-like file, then it could be displayed in the extension source viewer.

https://edge.microsoft.com/extensionwebstorebase/v1/crx?response=redirect&prod=chromiumcrx&prodchannel=&x=id%3D<<EXTENSION_ID>>%26installsource%3Dondemand%26uc

This what you're looking for?  I tried (briefly) with your online site using the URL but it errored... but I was able to grab extensions using chrome, curl, and wget without issue.  When manually uploaded the crx opened without issue on the website.

**Comment by Rob--W** [comment]
This is now supported in version 1.6.12. I referred to #95 in the changelog, but it should have been this issue.
