### ISSUE TITLE
License

### ISSUE THREAD

**Issue by yfdyh000** [Rob--W/crxviewer#44]
Is "All rights reserved"? Sad to see it on an open source software. In package.json, README.md and addons.opera.com.

Also, https://addons.mozilla.org/firefox/addon/crxviewer/ listed as "Released under Mozilla Public License, version 2.0" for now.

**Comment by Nefari0uss** [comment]
Reading [here](https://opensource.stackexchange.com/questions/2121/mit-license-and-all-rights-reserved), as far as I understand, `All rights reserved` does not grant any permissions to distribute/manipulate/modify the code without express permission ([no license](https://choosealicense.com/no-license/)) where as the [MPL](https://choosealicense.com/licenses/mpl-2.0/) does (along with some other stuff).

I've always found [this](https://choosealicense.com/) site to be helpful when picking a license.

**Comment by JustOff** [comment]
@Rob--W, I'm considering the possibility of porting your extension to the XUL platform, at least for my own purposes. I would be very grateful if you add a permissive license to your source code so I could release a public version of my fork for users of browsers that do not support WebExtensions.

**Comment by Rob--W** [comment]
I have now consciously decided to use the MPL-2.0 license. TL;DR = https://tldrlegal.com/license/mozilla-public-license-2.0-%28mpl-2%29
