### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by yfdyh000** [Rob--W/crxviewer#45]
```
>node --version
v8.1.4
```
```
>node make.js

Building Chrome extension...
D:\repo\crxviewer\external\builder.js:85
    line = line.replace(/__[\w]+__/g, function(variable) {
               ^

TypeError: Cannot read property 'replace' of undefined
    at expand (D:\repo\crxviewer\external\builder.js:85:16)
    at preprocess (D:\repo\crxviewer\external\builder.js:155:13)
    at D:\repo\crxviewer\external\builder.js:306:7
    at Array.forEach (native)
    at D:\repo\crxviewer\external\builder.js:300:13
    at Array.forEach (native)
    at Object.build (D:\repo\crxviewer\external\builder.js:295:20)
    at build (D:\repo\crxviewer\make.js:72:13)
    at Function.target.chrome (D:\repo\crxviewer\make.js:128:5)
    at Object.global.target.(anonymous function) [as chrome] (D:\repo\crxviewer\node_modules\shelljs\make.js:36:40)
```

**Comment by Rob--W** [comment]
Did you modify the source before building? For example did you add `//#expand` anywhere (or removed the end of the `//#expand` line in src/crxviewer.html)?

**Comment by yfdyh000** [comment]
No modification.

Maybe it is not compatible with non-ASCII characters in the path, I removed it ("存档") from this log.
Looks working on Bash on Windows, with node and 7z command installed and without non-ASCII characters in the path.

**Comment by Rob--W** [comment]
This error message is independent of the path name. The relevant part of the code is:

https://github.com/Rob--W/crxviewer/blob/2be4f038f5b9b851f1f63cd082bd016dc425336b/external/builder.js#L110-L112
https://github.com/Rob--W/crxviewer/blob/2be4f038f5b9b851f1f63cd082bd016dc425336b/external/builder.js#L118-L122
https://github.com/Rob--W/crxviewer/blob/2be4f038f5b9b851f1f63cd082bd016dc425336b/external/builder.js#L153-L155
https://github.com/Rob--W/crxviewer/blob/2be4f038f5b9b851f1f63cd082bd016dc425336b/external/builder.js#L84-L85

The above code path is only triggered for:

https://github.com/Rob--W/crxviewer/blob/2be4f038f5b9b851f1f63cd082bd016dc425336b/src/crxviewer.html#L4

The only way that this code could trigger the error is if the regular expression fails to capture the text after `#expand`, i.e. if the following regular expression does not match (`m[2]` in the code above refers to `(.*?)` in the part of the regexp below):

    (?:\s+(.*?)(?:-->)?$)

**Comment by yfdyh000** [comment]
I've gone through a few strange bugs and then it's working now. Two main points:
1. crlf in Windows. needs `autocrlf = false` in git and re-create files.
2. `7z` must exist in %PATH%.

Other strange bugs are not understood and not reproducible now.
