### ISSUE TITLE
_metadata sometimes not hidden

### ISSUE THREAD

**Issue by yfdyh000** [Rob--W/crxviewer#49]
View the crx of https://chrome.google.com/webstore/detail/surfingkeys/gfbliohnnapiefjpjlpjnehglfpaknnc.
`_metadata/verified_contents.json` is shown.

**Comment by Rob--W** [comment]
`_metadata/` is never hidden. I also don't intend to hide any file or directory from the view, because that would allow someone to hide malicious code.

If you are not interested in seeing "_metadata", just untick the "misc" checkbox.
