### ISSUE TITLE
Firefox Nightly Icon in locationbar always visible

### ISSUE THREAD

**Issue by Acid-Crash** [Rob--W/crxviewer#51]
On latest Firefox Nightly build 58.0a1 (2017-11-02) (64-bit) icon is always visible in locationbar disregarding the Settings option "Show a page action button in the locationbar of extension installation pages"

**Comment by Rob--W** [comment]
It worked for me in an earlier Nightly. I did a bisect with `mozregression` and found that the feature regressed in https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=7f19b2c7adc598f40bf32808324bcba463cce627&tochange=9f83f552a6118f1061ee5afd87578d9b5b82b308 when https://bugzilla.mozilla.org/show_bug.cgi?id=1395387 landed.

It seems that Tim has already reported the bug upstream at https://bugzilla.mozilla.org/show_bug.cgi?id=1413574

**Comment by Rob--W** [comment]
This bug has been fixed in Firefox. Users on stable will never be affected by this.
