### ISSUE TITLE
Request: Google Chrome Malware Check

### ISSUE THREAD

**Issue by CruaverVoidDrake** [Rob--W/crxviewer#53]
An option to check the plugin for malware either by accident or that Google might construe as malware for removal so the plugin can work without being shut down by Google.

**Comment by Rob--W** [comment]
The Chrome Web Store uses a combination of static analysis, dynamic analysis and manual review to detect malicious extensions ([paper](https://research.google.com/pubs/archive/43824.pdf)). The data used to support these systems are not public.

If you develop extensions in good faith, then your extension should not be shut down by Google. If you believe that your extension exhibits behavior that can be misconstrued as malicious, try to remove such behavior from the extension and then you shouldn't have to worry about being flagged and removed.
