### ISSUE TITLE
Error when downloading an extension from Chrome Webstore

### ISSUE THREAD

**Issue by dufferzafar** [Rob--W/crxviewer#55]
I'm using Firefox, and while trying to download/view this extension: https://chrome.google.com/webstore/detail/lightweight-phishing-dete/jielndbgelplgdkgaeikbhjkippcdjcp?hl=en

The following error occurs:

```
Failed to load https://clients2.google.com/service/update2/crx?response=redirect&os=linux&arch=x86-64&nacl_arch=x86-64&prod=chromiumcrx&prodchannel=unknown&prodversion=9999.0.9999.0&x=id%3Djielndbgelplgdkgaeikbhjkippcdjcp%26uc. Server responded with 403 Forbidden
```

**Comment by Rob--W** [comment]
The response has HTTP status code 401 (Unauthorized).

In Chrome, that web store page shows "Sign in to add". I think that in order to load that CRX file, one must sign in to a Google account. Are you signed in?
