### ISSUE TITLE
Clone in the ChromeStore

### ISSUE THREAD

**Issue by mikhoul** [Rob--W/crxviewer#57]
There is a clone in the Chrome Web store, the option panel even show a link here and show your name. 

https://chrome.google.com/webstore/detail/chrome-extension-source-c/ccecihahjmplendgebiobdabbmnllnan/related

Regards :octocat:

**Comment by Rob--W** [comment]
Thanks for the report. They have cloned version 1.6 of my extension, modified some files (code transformation without any apparent change in functionality) and slapped a new icon on it.
These unscrupulous people even copied my description and screenshots...

Fortunately, the authors have not modified the code in a malicious way yet.

I have filed a DMCA complaint at https://support.google.com/legal/contact/lr_dmca?product=chromewebstoreextensionsgallery&uraw=&hl=en .

Allegedly, a copy of the complaint will eventually be uploaded to https://www.lumendatabase.org/

**Comment by Rob--W** [comment]
... and it's gone, 45 minutes after the report.

> Hello,
>
>Thanks for reaching out to us.
>
>In accordance with the Digital Millennium Copyright Act, we have completed processing your infringement notice. We are in the process of disabling access to the content in question at the following URL(s):
>
>https://chrome.google.com/webstore/detail/chrome-extension-source-c/ccecihahjmplendgebiobdabbmnllnan?hl=EN
>
>The content will be removed shortly.
>
>Regards,
>The Google Team
