### ISSUE TITLE
Doesn't recognise Chrome extensions on Chrome Canary

### ISSUE THREAD

**Issue by lflee** [Rob--W/crxviewer#60]
It doesn't work on the current version of Chrome Canary (68.0.3404.0). The icon at the Toolbar is dimmed when at an extension URL on chrome.google.com/webstore/

**Comment by lflee** [comment]
By following the steps you presented, it works.

Try this -
1. Visit chrome://extensions
2. Click "Details" of an installed extension
3. Click "View in Chrome Web Store"
With these steps, the button is dimmed.
Apparently, the URL is the same by following my and your set of steps.

**Comment by Rob--W** [comment]
I followed your steps and the button is still visible:

1. Launch Chromium 68.0.3405.0 with a new profile.
2. Install the extension from https://chrome.google.com/webstore/detail/chrome-extension-source-v/jifpbeccnghkjeaalbbjmodiffmgedin
3. Visit `chrome://extensions/?id=jifpbeccnghkjeaalbbjmodiffmgedin`
4. Click on the "View in Chrome Web Store" link.

**Comment by lflee** [comment]
I still can reproduce the symptom in a new Chrome profile.
Browser: Chrome Canary (68.0.3405.0) for Windows 

Chrome Stable (66.0.3359.117) for Windows doesn't have this symptom.

**Comment by Rob--W** [comment]
Can you still reproduce this problem? I want to release a new version within a few days, and if you still have this bug I'd like to reproduce it.
