### ISSUE TITLE
Unexpected crx format version number

### ISSUE THREAD

**Issue by djcanard** [Rob--W/crxviewer#62]
I created a CRX file locally using Chrome 66.0.3359.139 (Windows 64-bit).
When I try to open it with CRX Viewer extension or on https://robwu.nl/crxviewer/ I get the message "Unexpected crx format version number."

I inspected the CRX file and it seems the CRX file format version is 3 while the CRX Viewer only seems to support version 2.
Hex header is: 43 72 32 34 03 00 00 00

**Comment by Rob--W** [comment]
Thanks for this report! It seems that the change was introduced here:

https://chromium.googlesource.com/chromium/src/+/b8bc9f99ef4ad6223dfdcafd924051561c05ac75%5E%21/
https://bugs.chromium.org/p/chromium/issues/detail?id=720092

I'll have to check for the difference and update https://github.com/Rob--W/crxviewer/blob/master/src/lib/crx-to-zip.js if needed.

**Comment by Rob--W** [comment]
I've fixed this, and will publish an update within a few days after tackling some other issues.
