### ISSUE TITLE
noob Question: scripts in TM

### ISSUE THREAD

**Issue by tirespider** [Rob--W/crxviewer#65]
Is it possible to get the "live" version of a script loaded with TamperMonkey?  As an example of what I mean, consider a script that creates a moveable box which opens at either the given default or the last set location.  When that box moves, I'm supposing, the in-memory script is updated with the new coordinates before being saved to file.  I want to know the currently set coords.  I've poked around TM but all I can find is the original script and I'm not certain how or where that data gets saved to.  Wouldn't it be in one of the modules under TM?  If so I can't seem to find it.  This could be a question or a feature request, idk.

Specifically, this concerns a script called TABS V2 (17.06.07), if that helps, but I would like a generalized answer regarding current data of scripts under TM.

**Comment by Rob--W** [comment]
Extensions cannot access storage of other extensions, so I cannot offer the ability to view user scripts inside Tampermonkey.
