### ISSUE TITLE
Avoid  404 NOT FOUND responses?

### ISSUE THREAD

**Issue by grahamperrin** [Rob--W/crxviewer#66]
For example, when I use CRX Viewer at https://addons.mozilla.org/addon/send-to-spillo/ with this user agent string (on FreeBSD-CURRENT): 

`Mozilla/5.0 (X11; FreeBSD amd64; rv:56.2) Gecko/20100101 Firefox/56.2 Waterfox/56.2`

> `Failed to load https://addons.mozilla.org/firefox/downloads/latest/send-to-spillo/platform:2/send-to-spillo.xpi. Server responded with 404 NOT FOUND`

Workaround: I can change the UA string to one for a platform that matches the requirement of an extension, e.g. 

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:52.0) Gecko/20100101 Firefox/52.0`

– but I wonder whether there's any way for CRX Viewer to 'intelligently' work around without manual intervention.

**Comment by Rob--W** [comment]
In this specific example, it seems that the extension is only available on macOS.

The viewer should support a way to change platform information, as already done for the Chrome Web Store (click on the "Open" link in the upper-right corner for an example).

The server-side logic to select a xpi file is at:

- https://github.com/mozilla/addons-server/blob/aaf9bf7689d13f077b7dbff412f2fb9d2e2f5e72/src/olympia/versions/views.py#L153-L166
- https://github.com/mozilla/addons-server/blob/24b9286625d4c8e21de3594d10e403908d03cfc7/src/olympia/constants/platforms.py#L8-L63

**Comment by grahamperrin** [comment]
Smart! 

So (for example) with 1.6.6 I browsed and arrived at: 

moz-extension://5b0f4f55-fc02-49f4-9d6f-03183fcfa2dc/crxviewer.html?crx=https%3A//addons.mozilla.org/firefox/downloads/file/988957/send_to_spillo-1.0-an%2Bfx-mac.xpi
