### ISSUE TITLE
Viewing source not working anymore!

### ISSUE THREAD

**Issue by EC-O-DE** [Rob--W/crxviewer#67]
:(
No source available at Opera Addons. 
Tried both the old version from Opera Addons and latest from CWS.

Functionality is not there. This renders this extension almost completely useless :/

**Comment by ngyikp** [comment]
I tried downloading a sample addon (https://addons.opera.com/en-gb/extensions/details/install-chrome-extensions/ ) with both Chrome 69.0.3472.3 and Opera 53.0.2907.99, and it works fine for me.

Is there a demo URL that isn't working for you? What browser?

**Comment by Zalext** [comment]
As I have seen, the url to download the Opera Addons doesn't points to a language site.

![2018-07-07_211643](https://user-images.githubusercontent.com/28935637/42414089-423a5db8-822e-11e8-8486-a8257a9eb6a2.png)


Could this be the problem?

**Comment by EC-O-DE** [comment]
yes

**Comment by Zalext** [comment]
@ngyikp 
At least in my case is happening on latests Opera Stable and Dev.

Using the [online CRX viewer](https://robwu.nl/crxviewer/) I've been able to download a couple of extensions, so I don't understand what's the point on the "broken"? extension.

Will this be addressed?

Thank you.

**Comment by Rob--W** [comment]
I can reproduce. Recent Opera versions (tested Opera 54) prevent extensions from directly connecting to addons.opera.com.

I have applied a work-around in version 1.6.6 and submitted an update for review to Opera's add-on gallery.

**Comment by Zalext** [comment]
Thank you Rob--W.

In my case, even the 1.6.6 doesn't work.
Still failing with the "Network error".

I'll use the web version meanwhile.


Thank you.

**Comment by Rob--W** [comment]
@Zalext Please provide your Opera version and your exact reproduction steps. Pasting the full URL of the extension also helps. Opera hides extension URLs by default IIRC, so to get the URL, open the DevTools panel, run `document.URL` and copy the link.

**Comment by Zalext** [comment]
Hi @Rob--W,

I've tested using latest OStable 55.0.2994.37 and Dev 56.0.3045.0.

I'll make a video on the steps.

----

Despite that, we can wait for September.

Thanks for your support.

**Comment by Rob--W** [comment]
@Zalext I've published a new update, which should fix the issue for real this time.
