### ISSUE TITLE
crx.dam.io certificate expired

### ISSUE THREAD

**Issue by grahamperrin** [Rob--W/crxviewer#68]
https://crx.dam.io/source/crxviewer.html

> … certificate expired on 4 July 2018, 12:44. The current time is 5 July 2018, 21:00.

**Comment by krystian3w** [comment]
https://github.com/mdamien/chrome-extensions-archive/issues

**Comment by Rob--W** [comment]
https://crx.dam.io hosts an old version of this viewer. Use https://robwu.nl/crxviewer/ instead.

(@mdamien The certificate of crx.dam.io has expired - see this issue. Also consider upgrading to the latest version of the viewer)

**Comment by grahamperrin** [comment]
Thanks / apologies for mis-filing in the wrong repo
