### ISSUE TITLE
Some Chrome extensions cannot be downloaded

### ISSUE THREAD

**Issue by csmk** [Rob--W/crxviewer#73]
As reported [here](https://github.com/Eloston/ungoogled-chromium/issues/448#issuecomment-424595808) and [here](https://github.com/Eloston/ungoogled-chromium/issues/531#issuecomment-425337019), some extensions (e.g. [HTTPS Everywhere](https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp), [Privacy Badger](https://chrome.google.com/webstore/detail/privacy-badger/pkehgijcmpdhfbdbbnkijodmdjhbjlgp)) cannot be downloaded.

![chrome_ext_bug](https://user-images.githubusercontent.com/2107715/46193267-86aefd00-c338-11e8-9e3d-db1bce4df7c7.png)

**Comment by Rob--W** [comment]
Fixed in 1.6.8. I've updated the documentation at https://stackoverflow.com/a/14099762/938089

**Comment by csmk** [comment]
Much appreciated for the quick fix. 👍
