### ISSUE TITLE
WebAssembly source code (.wat) is not recognized as text file

### ISSUE THREAD

**Issue by gwarser** [Rob--W/crxviewer#76]
It's only for reviewers, compiled code (.wasm) is binary.

Example https://robwu.nl/crxviewer/?crx=https%3A%2F%2Faddons.mozilla.org%2Ffirefox%2Fdownloads%2Flatest%2Fublock-origin%2Fplatform%3A2%2Fublock-origin.xpi&q=.wat&qf=lib%2Flz4%2Flz4-block-codec.wat

Shows dialog with:

>No handler for application/octet-stream :(
Want to open as plain text?

![image](https://user-images.githubusercontent.com/886325/49660604-48743f00-fa47-11e8-8038-cb8aef6fbcf6.png)

I'm on Manjaro, Firefox 63, 65, Chromium 71.

**Comment by Rob--W** [comment]
I have added support for WAT files, but not published an update yet.

Keep in mind that there is no guarantee that a .wat file matches the executed code. The only true executable code is in the .wasm file, but that is obviously not human-readable.

A potential way to achieve human-readability while also offering verification is to translate the wat and wasm files to a canonical representation and see whether they match. I'm not sure if this would always work though (e.g. if there is not only one canonical representation, then the validation may fail). WABT contains tools that can be used to build something like this: https://github.com/webassembly/wabt

I'm currently not interested in investing the time to build that though.

**Comment by Rob--W** [comment]
Published as version 1.6.10.
