### ISSUE TITLE
Show Total Uncompressed file size [FR: web viewer]

### ISSUE THREAD

**Issue by qpongo** [Rob--W/crxviewer#78]
It would be helpful to also **see the sum of the uncompressed file sizes in the file list** so that one can get a sense of how big the total extension is.

It would also be cool if you could click multiple files so that you can add up how big the files constituting the content script are.

**Comment by Rob--W** [comment]
The file size of individual files is shown in the file list, and precise values can be seen when you hover over the "Show download" / "Download file" link at the upper-left corner of each file in the viewer.

I'm not showing the sum of all uncompressed files though.

If I were to show it, I think that adding it to the tooltip of the Download link (of the zip file) would make most sense, such as done in #3 for the (compressed) size of the zip file.

**Comment by Rob--W** [comment]
This feature has been added to version 1.6.10.
