### ISSUE TITLE
Browser Console shows the wrong Extension ID for any Chrome WebStore extension URL

### ISSUE THREAD

**Issue by paronos** [Rob--W/crxviewer#83]
Apparently, CRX Viewer is able [get Key in the Browser Console](https://stackoverflow.com/a/21500707). [[#82](https://github.com/Rob--W/crxviewer/issues/82#issue-427442137)]

However, any Chrome WebStore URL opened in [CRX Viewer](https://robwu.nl/crxviewer/crxviewer.html) always reports the same message '**Calculated extension ID: lfoeajgcchlidpicbabpmckkejpckcfb**' in the Browser Console, meaning the 'Public key' is already incorrect. From what I understand, the [app ID](https://developer.chrome.com/webstore/publish#get-the-app-id) should match the Chrome WebStore URL's [Extension ID](https://chrome.google.com/webstore/detail/aaaaaaaaaabbbbbbbbbbcccccccccc?hl=en).

In fact, '**Download original CRX file**' button actually downloads a modified crx file, different from the official Chrome WebStore extension.

> [Chrome WebStore URL for test](https://chrome.google.com/webstore/detail/boostaler/jckhjkeamaabikcpkgchmnkcflnibahk?hl=en)
> Browsers: [CD V73.0.3683.75](https://www.comodo.com/home/browsers-toolbars/browser.php) & [CID V64.0.4.15 (Firefox/60.0)](https://www.comodo.com/home/browsers-toolbars/icedragon-browser.php)

![crxviewer Web Interface: ExtID](https://user-images.githubusercontent.com/23290139/57795717-41c9c080-7779-11e9-871f-cb6ad7a4fa35.png)

### Current workaround:
* Download crx files from https://crxextractor.com or https://chrome-extension-downloader.com which provide the [direct download URL](https://chrome-extension-downloader.com/how-does-it-work.php) of any Chrome extension
* Load the local crx file onto [CRX Viewer](https://robwu.nl/crxviewer/crxviewer.html) to get the correct Key

**Comment by Rob--W** [comment]
The difference in CRX file is caused by https://github.com/Rob--W/crxviewer/commit/d60ccdce84b25554f1343f4a77e6248bef82eba9

The CRX file is in the CRX3 file format. Apparently, there can be multiple public keys in the message, and the first occurrence is no longer the extension's public key. The parser needs to be updated to pick the right public key.

For example, if I download the CRX of the current version of CRX Viewer ([crxviewer_1.6.10-crx3.zip](https://github.com/Rob--W/crxviewer/files/3186933/crxviewer_1.6.10-crx3.zip)), extract the header and parse it, then I see the following (the first public key is apparently shared by CRX3 files from the Chrome Web Store; the second key is the extension's):

```sh
# crx3.proto from https://cs.chromium.org/codesearch/f/chromium/src/components/crx_file/crx3.proto
# 1061 is the length of the header section for this example
$ head -c 1061 crxviewer_1.6.10-crx3.zip | tail -c+13 | protoc --decode=crx_file.CrxFileHeader crx3.proto 
sha256_with_rsa {
  public_key: "0\202\001\"0\r\006\t*\206H\206\367\r\001\001\001\005\000\003\202\001\017\0000\202\001\n\002\202\001\001\000\217\373\277\\7c\224<\260\356\001\304\265\246\232\261\237Fto\0268\2402\'5\335\360qk\016\334\366%\313\262\355\352\3732\325\257\036\003C\003F\360\2479\333#\226\035e\345xQ\360\204\260\016\022\254\016[\334\311\326L|\000\325\270\033\2103>/\332\353\252\367\032u\302\256:T\3367\217\020\322(\346\204yM\025\264\363\275?V\323<?\030\253\374.\005\300\036\0101\266a\320\375\237O?d\r\027\223\274\255A\307H\276\000\'\250MpB\222\005T\246m\270\336Vn Ip\356\020>k\322|1\275\033n\244<Fb\237\010f\223\371*Q1\250\333\265\235\271\017s\350\240\t2\001\351{*\2126\240\317\027\260Pp\235\242\371\244obM\266\3111\374\363\010\022\377\223\275b1\330\034\352\032\236\365\201(\177u^\322\'z\302\226\365\235\333\030\374v\334F\360W\300X4\310\"-*eu\247\331\010b\315\002\003\001\000\001"
  signature: "F9\311m\304\306\200\0240\033/\277;\3349u\334\370\252/\207\037\332\3340\212E\211\350^\311\325\026\302p<Qg\200bQ\320@^\226q\353w\243j\330L\226\273\273\354R0\031(\256\357\002\245\263\312\364u\364;nv\275\013\277\277B,;G\233\004Tv\005\265\3576\211\320\031\277\337\243\271\306\200\007\314-\277\326\345A\177\312\014_\372\263\265\035\237\316(\336\266\201\224\354\266d\016\236hT\2552\275\036\323p\212\001\274\005\346\247\225\304Vj\345\324\320\006\227=^)gG\315\313\036\261$I\212\212J\021\373\223\244b\230\242\263\332.\355\216\363\016\270i\334%~C\347\353e\213f\362\210\277\256\331\364\034\016\326\370uaGb\276\207\320D.\356+\231Z\023\252\260\355\305\257\333\315I6\022\332E5\242\226\017\307L\244@\370\375\331\010\242f\314\242\274\317\310\177\346\323\244\302\242\251d\326\346\276\251\304p\255"
}
sha256_with_rsa {
  public_key: "0\201\2370\r\006\t*\206H\206\367\r\001\001\001\005\000\003\201\215\0000\201\211\002\201\201\000\215\305\267\230o\031\314\007\322\373\363\300\013~\005\232\316\224\252|{2\224W\327\244Y\236\207G\201\246\271\311+7\353\2500\351Z\272\357\002\205>\234\240\t\311\203\303\240Ha\023\353Y)\325\305\361\253\216`\223\326\010t8\010\353*\3164\"\233\216\007\277\347\274\022d\254\020\036\n\336\326Fv\026\230}\337\010D\234\331\376\365T\324\206sZ\347\325\370\021\242\364\321\313\201q>u\242\266z(\365f;\343\343\002\003\001\000\001"
  signature: "\211\255\317em\214K}!\345\275\221\355\230\014\002q\216i\276\306R\024\013K\335\014Pbxnu\r<\306\034\007\0338 l\3438\'\243\016Yz\037\341+\021\260\0216\245\343\364&\026\312\231\220t\312{\354q\324k\344P\205\272\276\211\253\023\031\305y\245\037\013\022Z\2475a\205\23022\022\310\0078\016\300}\304M\274\306\252d\001\214\242\333U\306\003\305\332[\3444V8\025D\247\210\025\252\272x"
}
sha256_with_ecdsa {
  public_key: "0Y0\023\006\007*\206H\316=\002\001\006\010*\206H\316=\003\001\007\003B\000\004\264\002\371\251\034\256\341\014\204\370\334\233\027r\230\245\3402\325\333+Y\330I\300\357\276\350k\371\370bR\270j5Sl\007\2138\324\377\232\335\274\335\371\274H\"i\314-l\241\001`\264Q\343{\321\317"
  signature: "0E\002 \021\215\302\021n^\327z3\316\200\023\036\263hgt\037\344\201\322~\203\3739QC{\210\245\032\365\002!\000\365\342J\263NPs)\227\270MY\007\2029\244\301O\243rX\321\302\262$tvZLv\212\202"
}
signed_header_data: "\n\020\230_\024\"\326z\224\000\261\031\3168U\306C\215"
```

**Comment by Rob--W** [comment]
I fixed this in the master branch and published an update to https://robwu.nl/crxviewer already. Now you can input the extension ID (or select a CRX file that you downloaded via the extension) and see the correct public key at the web version.

Since this feature is not exposed to the user interface (merely via the console), I will not immediately publish an update. The next update should hopefully include: https://github.com/Rob--W/crxviewer/issues/82 (this will take at least three more weeks).

**Comment by kzahel** [comment]
Thanks for fixing this, Rob. I was able to your website instead of the extension and got the correct id.
