### ISSUE TITLE
Doesn't work on opera.

### ISSUE THREAD

**Issue by carloscs** [Rob--W/crxviewer#85]
Doesn't work on opera.

Trying to view source for this extension, shows this message on the new tab; "Network error for https://addons.opera.com/extensions/download/extension-source-viewer/".

Same message (with the corresponding extension name) for the half a dozen extensions I tried to view the source.

Probably some incompatible change on the opera addons.

**Comment by carloscs** [comment]
Note: doesn't work just for opera addons. If I invoke on opera for a chrome addon it works. Must be some url problem with opera addons.

**Comment by Rob--W** [comment]
Which Opera version are you using?

I'll check later, but to see if it is an issue with the site or the browser, could you try an old version of Opera (e.g. 55 or 56) and see if the issue still occurs?

This issue happened before, but I fixed it back then in https://github.com/Rob--W/crxviewer/issues/67

**Comment by carloscs** [comment]
Developer Version: 64.0.3388.0.

I've just re-checked and it must be the browser (and not just with the extension): the online version at https://robwu.nl/crxviewer/ works on firefox and chrome but doesn't work on opera.

Have to se about getting a test version

**Comment by Rob--W** [comment]
Fixed in 1.6.11. I've uploaded an update, and it's currently awaiting approval.
