### ISSUE TITLE
https://robwu.nl/crxviewer/ 403 forbidden

### ISSUE THREAD

**Issue by grahamperrin** [Rob--W/crxviewer#88]
The same for https://robwu.nl/ as for https://robwu.nl/crxviewer/

> 403 Forbidden
> 
> ----
> 
> nginx/1.6.2

If it's routine maintenance: apologies for the noise.

**Comment by Rob--W** [comment]
Thanks for your report. I fixed it as soon as I saw it, but forgot to close this bug.
