### ISSUE TITLE
Extend to Firefox Marketplace

### ISSUE THREAD

**Issue by DanielHerr** [Rob--W/crxviewer#9]
It would be nice if this or another extension could view the source of Firefox Marketplace items, especially since they cannot be installed in Chrome OS.

**Comment by Lekensteyn** [comment]
Rob, what would it take to implement crxviewer as Firefox add-on?

FWIW, I have hacked crxviewer such that it can open an XPI file by drag-n-drop. UI can certainly be improved though, like adding a "Open other file" button on the crxviewer page. See https://github.com/Lekensteyn/crxviewer/compare/master...develop

**Comment by DanielHerr** [comment]
I might have found it. https://marketplace.firefox.com/api/v2/fireplace/app/whatever includes a "manifest_url". That file can include a "package_path".

**Comment by Rob--W** [comment]
@DanielHerr The example (8tracks) that I cited in https://github.com/Rob--W/crxviewer/issues/9#issuecomment-54731423 does indeed have a manifest_url pointing to http://8tracks.com/mobile/manifest.webapp, but this one does not have a package_path.

By the way, Firefox is experimenting with WebExtensions, which is an extension format that mimics the Chrome extension API. When this format stabilizes (and can be hosted on AMO), I may add support for that as well.

**Comment by DanielHerr** [comment]
I'm pretty sure that your example doesn't have a "package_url" because it isn't packaged,
hence "is_packaged": false

It isn't really necessary to add support for Firefox extensions since their extensions store has a button to download the xpi package.

**Comment by Rob--W** [comment]
Closing this bug because Firefox OS has been discontinued, and Firefox Marketplace was part of it.
