### ISSUE TITLE
A big big Bug - options page repeatedly resizes

### ISSUE THREAD

**Issue by dnknn** [Rob--W/crxviewer#94]
Hello, caught a big 🐞🐛🕷💥👿

When you use zoom: <kbd>Ctrl+Mouse-Wheel🎡</kbd>  It will blink all the time.

> ❖Win10 1903
> ֎CentBrowser (Chromium⁸⁰ kernel) http://www.centbrowser.com

![Bug🐞](https://user-images.githubusercontent.com/10995302/85435041-7da89980-b5b9-11ea-91f8-574df53d6b75.gif)

**Comment by Rob--W** [comment]
Thanks for your report. Does this only happen after zooming, or also without zooming (at 100%)?

Could you visit `chrome://version` and show the version of Chromium that you're using?

**Comment by dnknn** [comment]
> Does this only happen after zooming, or also without zooming (at 100%)?
I don't know, anyway, I inadvertently debug is related to zoom.

mdff<details>
<summary>Sys-zoom Pic</summary>
![image](https://user-images.githubusercontent.com/10995302/85453154-23fe9a00-b5ce-11ea-9a05-1d33c6731253.png)


</details>


<details>
<summary>֎version</summary>

Cent Browser | 4.2.10.171 (正式版本) （64 bit）
用户代理 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
修订版本 | e7fbe071abe9328cdce4ffedac9822435fbd3656-refs/branch-heads/3987@{#1037}
操作系统 | Windows 10 OS Version 1903 (Build 18362.900)
JavaScript | V8 8.0.426.30
Flash | 32.0.0.363
Command Line | "C:\XXXX\Cent Chrome\centbrowser_4.2.9.152_x64_portable\chrome.exe" --cb-disable-answers-in-suggest --cb-disable-auto-detect-search-provider --flag-switches-begin --enable-features=NativeNotifications,TabHoverCards --disable-features=OmniboxUIExperimentHideSteadyStateUrlTrivialSubdomains --flag-switches-end --enable-audio-service-sandbox


</details>

**Comment by dnknn** [comment]
I can reproduce 🐞 it on Google Chrome.

**Comment by Rob--W** [comment]
Which Chrome version are you using? I'm going to file a bug report there.

**Comment by dnknn** [comment]
> Which Chrome version are you using? I'm going to file a bug report there.

In the later versions of Google, at least I know the Chrome69+ and later versions. A large part of the extensions -options pages have abnormal behavior, especially not adaptive display.
Of course, you can open a separate setting options page, for example
chrome-extension://jifpbeccnghkjeaalbbjmodiffmgedin/options.html#optionsV2

**Comment by Rob--W** [comment]
Are you able to test this with the latest version of Chrome?

Does this bug only happen with my extension, or also others?

**Comment by dnknn** [comment]
> Does this bug only happen with my extension, or also others?

Gif demo 🐞 for only your extension

**Comment by dnknn** [comment]
A common problem with other extensions is another problem with width.

![0624040707](https://user-images.githubusercontent.com/10995302/85455416-750f8d80-b5d0-11ea-98e5-8b51213cb193.png)

![Bug3](https://user-images.githubusercontent.com/10995302/85455395-704ad980-b5d0-11ea-8887-c738ec533d12.gif)

**Comment by Rob--W** [comment]
I have filed a bug report at https://bugs.chromium.org/p/chromium/issues/detail?id=1098452

**Comment by dnknn** [comment]
I sent your 📧
